### PR TITLE
Bumps in garden : ign-garden

### PR DESCRIPTION
**Pull request by scpeters**
See ignition-tooling/release-tools#545

### CODE REVIEW

**Review by chapulina — APPROVED** [review]
:clap:

**Comment by chapulina** [comment]
btw, CI won't fail until #2 is merged

**Comment by chapulina** [comment]
`-- Looking for ignition-rendering7 - not found`

**Comment by scpeters** [comment]
> -- Looking for ignition-rendering7 - not found

~~~
  CMake Warning at /usr/share/cmake/ignition-cmake2/cmake2/IgnUtils.cmake:189 (find_package):
    Could not find a configuration file for package "ignition-rendering7" that
    is compatible with requested version "6.0.1".
~~~

thanks for the cmake check; that is finding an error, but I am confused as to where it is coming from

**Comment by scpeters** [comment]
> > -- Looking for ignition-rendering7 - not found
> 
> ```
>   CMake Warning at /usr/share/cmake/ignition-cmake2/cmake2/IgnUtils.cmake:189 (find_package):
>     Could not find a configuration file for package "ignition-rendering7" that
>     is compatible with requested version "6.0.1".
> ```
> 
> thanks for the cmake check; that is finding an error, but I am confused as to where it is coming from

ha nevermind

**Pull request merged**
